# Generated by Django 4.0.1 on 2022-01-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=300)),
                ('short_url', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
